#pragma once

#include "typedef.h";

struct IPM
{
	COEFFICIENTS c;
	INEQUALITY_CONSTRAINT_ARRAY A;
	INEQUALITY_CONSTRAINT_VECTOR b;

	IPM();
	IPM(COEFFICIENTS, INEQUALITY_CONSTRAINT_ARRAY, INEQUALITY_CONSTRAINT_VECTOR);
};