#pragma once

#include "typedef.h";

#ifndef STRUCT_IPM_H
#define STRUCT_IPM_H

struct IPM
{
	COEFFICIENTS c;
	INEQUALITY_CONSTRAINT_ARRAY A;
	INEQUALITY_CONSTRAINT_VECTOR b;

	IPM();
	IPM(COEFFICIENTS, INEQUALITY_CONSTRAINT_ARRAY, INEQUALITY_CONSTRAINT_VECTOR);
};

#endif